apiVersion: apps/v1
kind: Deployment
metadata:
  name: az-raga-kafka-producer-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: etm-kafka-producer
  template:
    metadata:
      labels:
        app: etm-kafka-producer
    spec:
      containers:
      - name: ragaetmdemo
        image: ragaetmdemo.azurecr.io/happykafkapoc:47
      imagePullSecrets:
      - name: acr-secret
